FROM bitnami/laravel:8.6.11

WORKDIR /app

USER root
COPY . .
ADD /docker/start.sh /docker
ADD .env.example .
ADD .env.testing.example .
RUN chmod +x ./docker/start.sh && apt update

USER bitnami

CMD ["./docker/start.sh"]
