FROM bitnami/laravel:8.6.11

WORKDIR /app

USER root
COPY . .
ADD /.env.example /.env.example
ADD /.env.testing.example /.env.testing.example
ADD /docker/start.sh /docker
RUN chmod +x ./docker/start.sh && apt update

USER bitnami

CMD ["./docker/start.sh"]
